name: Build Flask Docker Image

on:
  push:
    branches: [ Anaya, Test ]
  pull_request:
    branches: [ Anaya, Test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t flask-app -f Test/Dockerfile Test/

    - name: Test Docker Image (optional)
      run: |
        docker run -d -p 5000:5000 flask-app
